# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-10-08T03:43:30+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Any, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Type(StrEnum):
    DONE = "done"


class AssistDoneEvent(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["done"]


class Type1(StrEnum):
    ERROR = "error"


class AssistErrorEvent(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["error"]
    detail: str


class Type2(StrEnum):
    SQL = "sql"


class AssistSqlEvent(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["sql"]
    sql: str


class Type3(StrEnum):
    STATUS = "status"


class AssistStatusEvent(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Literal["status"]
    message: str


class Column(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str = Field(
        ..., description="Column name, de-duplicated within a result (a, a -> a, a_1)"
    )
    type: str | None = Field(
        ..., description="Backend-native type name; null when the backend can't say"
    )
    nullable: bool | None = Field(
        None, description="Whether the column accepts nulls; null when unknown"
    )


class ConnectorKind(StrEnum):
    SQLITE = "sqlite"
    DUCKDB = "duckdb"
    POSTGRES = "postgres"
    MYSQL = "mysql"


class CreateConnector(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str = Field(..., description="Connector display name", max_length=100)
    kind: ConnectorKind = Field(
        ..., description="Database backend; immutable after creation"
    )
    options: dict[str, Any] = Field(
        ..., description="Kind-specific options; see GET /v1/connections"
    )


class ExecuteRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    query: str = Field(..., description="SQL to run")
    params: list[Any] | dict[str, Any] | None = Field(
        None,
        description="DB-API parameters: an array for positional, an object for named",
    )
    max_rows: int | None = Field(
        1000, description="Maximum rows to return", ge=1, le=10000
    )


class ExecuteResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    columns: list[Column]
    data: dict[str, list[Any]] = Field(
        ..., description="Columnar rows: {column_name: [values...]}"
    )
    truncated: bool = Field(
        ..., description="True if the query produced more than max_rows rows"
    )


class GenerateRequest(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    prompt: str = Field(
        ..., description="What the query should do, in plain language", min_length=1
    )
    context: str | None = Field(
        None,
        description="The editor's full text, so the agent can refine an existing query",
    )


class HealthStatus(StrEnum):
    OK = "ok"
    DEGRADED = "degraded"


class OptionType(StrEnum):
    STRING = "string"
    INTEGER = "integer"
    BOOLEAN = "boolean"


class Kind(StrEnum):
    TABLE = "table"
    VIEW = "view"


class Table(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    path: list[str] = Field(
        ..., description='Hierarchical table identifier, e.g. ["main", "users"]'
    )
    kind: Kind = Field(..., description="Whether this is a table or a view")
    columns: list[Column]


class TableList(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    tables: list[list[str]] = Field(..., description="Table paths")


class UUIDModel(RootModel[UUID]):
    root: UUID


class UpdateConnector(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str = Field(..., description="Connector display name", max_length=100)
    options: dict[str, Any] = Field(
        ..., description="Kind-specific options; see GET /v1/connections"
    )


class Url(RootModel[str]):
    root: str


class AssistEvent(
    RootModel[AssistStatusEvent | AssistSqlEvent | AssistErrorEvent | AssistDoneEvent]
):
    root: AssistStatusEvent | AssistSqlEvent | AssistErrorEvent | AssistDoneEvent = (
        Field(..., discriminator="type")
    )


class Connector(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: UUIDModel = Field(..., description="Unique connector identifier")
    name: str = Field(..., description="Connector display name", max_length=100)
    kind: ConnectorKind = Field(
        ..., description="Database backend; immutable after creation"
    )
    options: dict[str, Any] = Field(
        ..., description="Kind-specific options; see GET /v1/connections"
    )
    created_at: AwareDatetime = Field(..., description="Creation timestamp")


class ConnectorOption(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str = Field(..., description="Option key, as used in Connector.options")
    type: OptionType
    description: str = Field(..., description="Human-readable description")
    required: bool
    default: Any | None = Field(
        None, description="Value used when the option is omitted"
    )
    secret: bool = Field(
        ...,
        description="Whether the value is sensitive (e.g. a password) and should be masked in UIs",
    )


class Health(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    status: HealthStatus = Field(..., description="Overall service status")
    version: str = Field(..., description="Deployed service version")


class Pagination(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    page: int | None = Field(1, description="Page number (1-indexed)", ge=1)
    page_size: int | None = Field(
        50, description="Number of items in this page, can be empty", ge=0, le=200
    )
    next: Url | None = Field(None, description="Link to next page if one exists")
    prev: Url | None = Field(None, description="Link to previous page if one exists")


class ProblemDetail(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    type: Url = Field(
        ..., description="A URI reference that identifies the problem type"
    )
    title: str = Field(
        ..., description="A short, human-readable summary of the problem type"
    )
    status: int = Field(
        ..., description="The HTTP status code for this occurrence of the problem"
    )
    detail: str | None = Field(
        None,
        description="A human-readable explanation specific to this occurrence of the problem",
    )
    instance: Url | None = Field(
        None,
        description="A URI reference that identifies the specific occurrence of the problem",
    )


class ConnectorKindInfo(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    kind: ConnectorKind
    name: str = Field(..., description='Display name, e.g. "PostgreSQL"')
    options: list[ConnectorOption] = Field(
        ..., description="Options in declaration order"
    )


class ConnectorKindList(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    kinds: list[ConnectorKindInfo]


class ConnectorPage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    items: list[Connector] = Field(..., description="Items in this page")
    pagination: Pagination = Field(..., description="Pagination parameters")
